title: DragonLab
description: Bienvenue sur dragonlab.ch
logo: /assets/img/logo-dragonlab.png

baseurl: ""
url: "https://www.dragonlab.ch"


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

